#!/usr/bin/env python
"""
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
  Copyright (C) 2018 Fernando Serena.
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

            http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
"""
import logging
import os

from agora import Agora, setup_logging

from agora_graphql.server import build

setup_logging(logging.DEBUG)

REQUEST_TIMEOUT = int(os.environ.get('REQUEST_TIMEOUT', 300))
API_PORT = int(os.environ.get('API_PORT', 5010))

__author__ = 'Fernando Serena'

if __name__ == '__main__':

    graphql_config = {
        'host': 'localhost',
        'port': 8000,
        'data_cache': {
            'min_cache_time': 300,
            'redis_file': 'cache.db'
        }
    }

    try:
        app = build(**graphql_config)
        app.run(host='0.0.0.0', port=API_PORT, use_reloader=False, debug=False, threaded=True)
    except (KeyboardInterrupt, SystemExit, SystemError):
        pass
    finally:
        Agora.close()
